language: node_js
node_js:
    - "7"

install:
    - npm install -g gulp karma-cli
    - npm install

script:
    - npm test

cache:
    directories:
    - node_modules

branches:
    only:
        - master
